### ISSUE TITLE
crash when encoding QR Code

### ISSUE THREAD

**Issue by sw55555** [wolever/libqrencode-cffi#1]
stack trace from core dump as follow, when trying to do multiple times of encoding

(gdb) py-bt-full 
#5 Frame 0x61739f0, for file /home/ckt/.local/lib/python2.7/site-packages/libqrencode/__init__.py, line 111, in __init__ (self=<QRCode(raw_data=[193, 193, 193, 193, 193, 193, 193, 192, 132, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 3, 3, 3, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 3, 3, 3, 2, 3, 2, 3, 2, 2, 2, 3, 2, 3, 3, 2, 3, 3, 3, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 136, 137, 136, 192, 193, 193, 193, 193, 193, 193, 193, 193, 192, 192, 192, 192, 192, 193, 192, 133, 3, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 3, 3, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 136, 137, 137, 192, 193, 192, 192, 192, 192, 192, 193, 193, 192, 193, 193, 193, 192, 193, 192, 132, 2, 3, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 3, 3, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 2...(truncated)
    func(arg)
#16 Frame 0x10df940, for file fault_test.py, line 14, in generate_qrcode (data='0,de7542005b9041eeb725643fa051576f,0,1,d03f65e4fc8047879b37ca39c670849c,0b8tuUlojoti1i4K1S553Vsg0JbAyEynuiZpk3jZ4iSAXE5q7hgEheT6zIyugWfl1839Vn0q61OPXDwoE2okYOOclTLuyRcl65XxSSPntb,prod,1502475119566,1502488886599,2|01c05ec81d744bfd9233dbb75a89b861,5w8ffcxoZkWV2jSrHbcXzcJwwR9M6bCThZIBIyqJ8Uq5L0wTgzYefXXpZqNQatfs6TaaO7e0FdQGtKT3wH7qtv9p2sWKb8JR7tg9GllJUD,prod,1502475119686,1502488886601,2|f16b5d0adcbe48d6b58f75259126b8ac,qqjmNtvIc4XEU5EC0u89sb6aFvTYiqdd7mJmQA7IJ7XeGT9GZJz7y5Igxmukn1NDrteXwBCiJigqBGbHGgnUTeUg0gtQAMmh2rnMycrN9p,test,1502475025625,1502488886602,2|7bbee40dd9dd4d79b66ec9afc4071bf5,17ob23AscYSRy3AqUR6PZRI43bOYvq8AQ3uSOHiuOyPoqGdkkNkGTfpPRX5rxwScEVAsgqt0m9YfaWMy8zIa5pEfSsPViQ4Fxp4ThDQihA,test,1502475025664,1502488886603,2', backgroud_width=1280, backgroud_height=1024, border=40, libqrencode=<module at remote 0x7f8f69bb9268>)
    qrcode = libqrencode.QRCode(data, error_correction=libqrencode.ECLEVEL_L)
#20 Frame 0x7f8f69c8aa60, for file fault_test.py, line 39, in test (data=u'0,de7542005b9041eeb725643fa051576f,0,1,d03f65e4fc8047879b37ca39c670849c,0b8tuUlojoti1i4K1S553Vsg0JbAyEynuiZpk3jZ4iSAXE5q7hgEheT6zIyugWfl1839Vn0q61OPXDwoE2okYOOclTLuyRcl65XxSSPntb,prod,1502475119566,1502488886599,2|01c05ec81d744bfd9233dbb75a89b861,5w8ffcxoZkWV2jSrHbcXzcJwwR9M6bCThZIBIyqJ8Uq5L0wTgzYefXXpZqNQatfs6TaaO7e0FdQGtKT3wH7qtv9p2sWKb8JR7tg9GllJUD,prod,1502475119686,1502488886601,2|f16b5d0adcbe48d6b58f75259126b8ac,qqjmNtvIc4XEU5EC0u89sb6aFvTYiqdd7mJmQA7IJ7XeGT9GZJz7y5Igxmukn1NDrteXwBCiJigqBGbHGgnUTeUg0gtQAMmh2rnMycrN9p,test,1502475025625,1502488886602,2|7bbee40dd9dd4d79b66ec9afc4071bf5,17ob23AscYSRy3AqUR6PZRI43bOYvq8AQ3uSOHiuOyPoqGdkkNkGTfpPRX5rxwScEVAsgqt0m9YfaWMy8zIa5pEfSsPViQ4Fxp4ThDQihA,test,1502475025664,1502488886603,2')
    img = generate_qrcode(data, 1280, 1024)
#23 Frame 0x7f8f6d5e0240, for file fault_test.py, line 45, in <module> ()
    test()

**Comment by wolever** [comment]
Thanks! Can you post a script I can use to reproduce?

**Comment by sw55555** [comment]
```python
import time
import numpy as np
from PIL import Image

import libqrencode

def generate_qrcode(data, backgroud_width, backgroud_height, border=40):
    """generate QR code according to data"""
    if isinstance(data, unicode):
        data = data.encode('utf8')
    qrcode = libqrencode.QRCode(data, error_correction=libqrencode.ECLEVEL_L)
    img = qrcode.get_im(border=0)
    width, height = img.size
    output_height = backgroud_height - 2 * border
    # resize image to target size
    if height != output_height:
        img = img.resize((output_height, output_height), Image.NEAREST)
        width, height = img.size

    # add white backgroud
    img = np.array(img.convert('L'))
    x, y = (backgroud_width - width) / 2, (backgroud_height - height) / 2
    back_img = np.full((backgroud_height, backgroud_width), 255, dtype=np.uint8)
    back_img[y: y + height, x: x + width] = img
    return back_img
        
def test():
    data = u'0,de7542005b9041eeb725643fa051576f,0,1,d03f65e4fc8047879b37ca39c670849c,0b8tuUlojoti1i4K1S553Vsg0JbAyEynuiZpk3jZ4iSAXE5q7hgEheT6zIyugWfl1839Vn0q61OPXDwoE2okYOOclTLuyRcl65XxSSPntb,prod,1502475119566,1502488886599,2|01c05ec81d744bfd9233dbb75a89b861,5w8ffcxoZkWV2jSrHbcXzcJwwR9M6bCThZIBIyqJ8Uq5L0wTgzYefXXpZqNQatfs6TaaO7e0FdQGtKT3wH7qtv9p2sWKb8JR7tg9GllJUD,prod,1502475119686,1502488886601,2|f16b5d0adcbe48d6b58f75259126b8ac,qqjmNtvIc4XEU5EC0u89sb6aFvTYiqdd7mJmQA7IJ7XeGT9GZJz7y5Igxmukn1NDrteXwBCiJigqBGbHGgnUTeUg0gtQAMmh2rnMycrN9p,test,1502475025625,1502488886602,2|7bbee40dd9dd4d79b66ec9afc4071bf5,17ob23AscYSRy3AqUR6PZRI43bOYvq8AQ3uSOHiuOyPoqGdkkNkGTfpPRX5rxwScEVAsgqt0m9YfaWMy8zIa5pEfSsPViQ4Fxp4ThDQihA,test,1502475025664,1502488886603,2'
    img = generate_qrcode(data, 1280, 1024)
    if img is None:
        print 'img is none!'
        
if __name__ == '__main__':
    for i in range(2000000):
        test()
        print time.time(), i
```

**Comment by sw55555** [comment]
I run this script on two machine, only one crash at the 2809, maybe something is wrong about my environment. I'll continue to do more test.

**Comment by sw55555** [comment]
After reinstall all python packages, this problem seems to go away. So this maybe caused by wrong configuration of my python environment. Thanks anyway!

**Comment by wolever** [comment]
Phew! Yea, I tried running it, and I wasn't able to reproduce the crash either. Glad it's working!
